import "@/styles/globals.css";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";
import { SiteFooter } from "@/components/site-footer";
import { SiteHeader } from "@/components/site-header";
import { FontWrapper } from "@/components/font-wrapper";
import { MaxWidthWrapper } from "@/components/max-with-wrapper";

export const metadata: Metadata = {
  title: "Home Page",
  description: "Generated by sahil kumar dev",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn("dark antialiased")}>
        <FontWrapper>
          <MaxWidthWrapper>
            <SiteHeader />
            <div className="min-h-[calc(100dvh-6rem)] lg:min-h-screen lg:max-h-screen place-items-center place-content-center px-4">
              {children}
            </div>
            <SiteFooter />
          </MaxWidthWrapper>
        </FontWrapper>
      </body>
    </html>
  );
}
